<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25949" started-at="2016-10-12T16:57:35Z" finished-at="2016-10-12T16:58:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25949" started-at="2016-10-12T16:57:35Z" finished-at="2016-10-12T16:58:01Z">
      <class name="testSuiteExpense.KPITilesVisual">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testSuiteExpense.KPITilesVisual@48eff760]" name="setUp" is-config="true" duration-ms="5868" started-at="2016-10-12T12:57:35Z" finished-at="2016-10-12T12:57:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="KpiTilesVisualTest()[pri:0, instance:testSuiteExpense.KPITilesVisual@48eff760]" name="KpiTilesVisualTest" duration-ms="16941" started-at="2016-10-12T12:57:40Z" finished-at="2016-10-12T12:57:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failure in ExpenseHelper.VerifyTotalExpenseCostFor input string: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failure in ExpenseHelper.VerifyTotalExpenseCostFor input string: ""
	at org.testng.Assert.fail(Assert.java:94)
	at helperObjects.ExpenseHelper.VerifyInteger(ExpenseHelper.java:83)
	at helperObjects.ExpenseHelper.VerifyContainsDollarAndKilo(ExpenseHelper.java:92)
	at helperObjects.ExpenseHelper.VerifyTotalExpenseCostAndTitle(ExpenseHelper.java:28)
	at testSuiteExpense.KPITilesVisual.KpiTilesVisualTest(KPITilesVisual.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- KpiTilesVisualTest -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:testSuiteExpense.KPITilesVisual@48eff760]" name="closeDriver" is-config="true" duration-ms="3125" started-at="2016-10-12T12:57:57Z" finished-at="2016-10-12T12:58:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- testSuiteExpense.KPITilesVisual -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
